[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256k1 = { version = "0.27", features = ["recovery"] }
ring = "0.17.8"
sha2 = "0.10.8"
solana-sdk = "2.2.0"
rand = "0.8.0"
